//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BarberShopTelas.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback inserirClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback removerClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback atualizarCLienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarClienteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::BarberShopTelas.Properties.Settings.Default.BarberShopTelas_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event inserirClienteCompletedEventHandler inserirClienteCompleted;
        
        /// <remarks/>
        public event removerClienteCompletedEventHandler removerClienteCompleted;
        
        /// <remarks/>
        public event atualizarCLienteCompletedEventHandler atualizarCLienteCompleted;
        
        /// <remarks/>
        public event listarClienteCompletedEventHandler listarClienteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/inserirCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void inserirCliente(Cliente c) {
            this.Invoke("inserirCliente", new object[] {
                        c});
        }
        
        /// <remarks/>
        public void inserirClienteAsync(Cliente c) {
            this.inserirClienteAsync(c, null);
        }
        
        /// <remarks/>
        public void inserirClienteAsync(Cliente c, object userState) {
            if ((this.inserirClienteOperationCompleted == null)) {
                this.inserirClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OninserirClienteOperationCompleted);
            }
            this.InvokeAsync("inserirCliente", new object[] {
                        c}, this.inserirClienteOperationCompleted, userState);
        }
        
        private void OninserirClienteOperationCompleted(object arg) {
            if ((this.inserirClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.inserirClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/removerCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void removerCliente(Cliente c) {
            this.Invoke("removerCliente", new object[] {
                        c});
        }
        
        /// <remarks/>
        public void removerClienteAsync(Cliente c) {
            this.removerClienteAsync(c, null);
        }
        
        /// <remarks/>
        public void removerClienteAsync(Cliente c, object userState) {
            if ((this.removerClienteOperationCompleted == null)) {
                this.removerClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoverClienteOperationCompleted);
            }
            this.InvokeAsync("removerCliente", new object[] {
                        c}, this.removerClienteOperationCompleted, userState);
        }
        
        private void OnremoverClienteOperationCompleted(object arg) {
            if ((this.removerClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.removerClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/atualizarCLiente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void atualizarCLiente(Cliente c) {
            this.Invoke("atualizarCLiente", new object[] {
                        c});
        }
        
        /// <remarks/>
        public void atualizarCLienteAsync(Cliente c) {
            this.atualizarCLienteAsync(c, null);
        }
        
        /// <remarks/>
        public void atualizarCLienteAsync(Cliente c, object userState) {
            if ((this.atualizarCLienteOperationCompleted == null)) {
                this.atualizarCLienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnatualizarCLienteOperationCompleted);
            }
            this.InvokeAsync("atualizarCLiente", new object[] {
                        c}, this.atualizarCLienteOperationCompleted, userState);
        }
        
        private void OnatualizarCLienteOperationCompleted(object arg) {
            if ((this.atualizarCLienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.atualizarCLienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/listarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cliente[] listarCliente() {
            object[] results = this.Invoke("listarCliente", new object[0]);
            return ((Cliente[])(results[0]));
        }
        
        /// <remarks/>
        public void listarClienteAsync() {
            this.listarClienteAsync(null);
        }
        
        /// <remarks/>
        public void listarClienteAsync(object userState) {
            if ((this.listarClienteOperationCompleted == null)) {
                this.listarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarClienteOperationCompleted);
            }
            this.InvokeAsync("listarCliente", new object[0], this.listarClienteOperationCompleted, userState);
        }
        
        private void OnlistarClienteOperationCompleted(object arg) {
            if ((this.listarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarClienteCompleted(this, new listarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cliente {
        
        private string cpfField;
        
        private string nomeField;
        
        private string telefoneField;
        
        /// <remarks/>
        public string Cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void inserirClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void removerClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void atualizarCLienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void listarClienteCompletedEventHandler(object sender, listarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591