//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BarberShopClasses.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback inserirClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback removerClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback atualizarCLienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback inserirProdutoOperationCompleted;
        
        private System.Threading.SendOrPostCallback removerProdutoOperationCompleted;
        
        private System.Threading.SendOrPostCallback atualizarProdutoOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarProdutoOperationCompleted;
        
        private System.Threading.SendOrPostCallback inserirServicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback removerServicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback atualizarServicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarServicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CadastrarAgendamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AtualizarAgendamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoverAgendamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarAgendamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarValorOperationCompleted;
        
        private System.Threading.SendOrPostCallback CadastrarPagamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoverPagamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarPagamentoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::BarberShopClasses.Properties.Settings.Default.BarberShopClasses_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event inserirClienteCompletedEventHandler inserirClienteCompleted;
        
        /// <remarks/>
        public event removerClienteCompletedEventHandler removerClienteCompleted;
        
        /// <remarks/>
        public event atualizarCLienteCompletedEventHandler atualizarCLienteCompleted;
        
        /// <remarks/>
        public event listarClienteCompletedEventHandler listarClienteCompleted;
        
        /// <remarks/>
        public event inserirProdutoCompletedEventHandler inserirProdutoCompleted;
        
        /// <remarks/>
        public event removerProdutoCompletedEventHandler removerProdutoCompleted;
        
        /// <remarks/>
        public event atualizarProdutoCompletedEventHandler atualizarProdutoCompleted;
        
        /// <remarks/>
        public event listarProdutoCompletedEventHandler listarProdutoCompleted;
        
        /// <remarks/>
        public event inserirServicoCompletedEventHandler inserirServicoCompleted;
        
        /// <remarks/>
        public event removerServicoCompletedEventHandler removerServicoCompleted;
        
        /// <remarks/>
        public event atualizarServicoCompletedEventHandler atualizarServicoCompleted;
        
        /// <remarks/>
        public event listarServicoCompletedEventHandler listarServicoCompleted;
        
        /// <remarks/>
        public event CadastrarAgendamentoCompletedEventHandler CadastrarAgendamentoCompleted;
        
        /// <remarks/>
        public event AtualizarAgendamentoCompletedEventHandler AtualizarAgendamentoCompleted;
        
        /// <remarks/>
        public event RemoverAgendamentoCompletedEventHandler RemoverAgendamentoCompleted;
        
        /// <remarks/>
        public event ListarAgendamentoCompletedEventHandler ListarAgendamentoCompleted;
        
        /// <remarks/>
        public event buscarValorCompletedEventHandler buscarValorCompleted;
        
        /// <remarks/>
        public event CadastrarPagamentoCompletedEventHandler CadastrarPagamentoCompleted;
        
        /// <remarks/>
        public event RemoverPagamentoCompletedEventHandler RemoverPagamentoCompleted;
        
        /// <remarks/>
        public event ListarPagamentoCompletedEventHandler ListarPagamentoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/inserirCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void inserirCliente(Cliente c) {
            this.Invoke("inserirCliente", new object[] {
                        c});
        }
        
        /// <remarks/>
        public void inserirClienteAsync(Cliente c) {
            this.inserirClienteAsync(c, null);
        }
        
        /// <remarks/>
        public void inserirClienteAsync(Cliente c, object userState) {
            if ((this.inserirClienteOperationCompleted == null)) {
                this.inserirClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OninserirClienteOperationCompleted);
            }
            this.InvokeAsync("inserirCliente", new object[] {
                        c}, this.inserirClienteOperationCompleted, userState);
        }
        
        private void OninserirClienteOperationCompleted(object arg) {
            if ((this.inserirClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.inserirClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/removerCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void removerCliente(Cliente c) {
            this.Invoke("removerCliente", new object[] {
                        c});
        }
        
        /// <remarks/>
        public void removerClienteAsync(Cliente c) {
            this.removerClienteAsync(c, null);
        }
        
        /// <remarks/>
        public void removerClienteAsync(Cliente c, object userState) {
            if ((this.removerClienteOperationCompleted == null)) {
                this.removerClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoverClienteOperationCompleted);
            }
            this.InvokeAsync("removerCliente", new object[] {
                        c}, this.removerClienteOperationCompleted, userState);
        }
        
        private void OnremoverClienteOperationCompleted(object arg) {
            if ((this.removerClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.removerClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/atualizarCLiente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void atualizarCLiente(Cliente c) {
            this.Invoke("atualizarCLiente", new object[] {
                        c});
        }
        
        /// <remarks/>
        public void atualizarCLienteAsync(Cliente c) {
            this.atualizarCLienteAsync(c, null);
        }
        
        /// <remarks/>
        public void atualizarCLienteAsync(Cliente c, object userState) {
            if ((this.atualizarCLienteOperationCompleted == null)) {
                this.atualizarCLienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnatualizarCLienteOperationCompleted);
            }
            this.InvokeAsync("atualizarCLiente", new object[] {
                        c}, this.atualizarCLienteOperationCompleted, userState);
        }
        
        private void OnatualizarCLienteOperationCompleted(object arg) {
            if ((this.atualizarCLienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.atualizarCLienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/listarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cliente[] listarCliente() {
            object[] results = this.Invoke("listarCliente", new object[0]);
            return ((Cliente[])(results[0]));
        }
        
        /// <remarks/>
        public void listarClienteAsync() {
            this.listarClienteAsync(null);
        }
        
        /// <remarks/>
        public void listarClienteAsync(object userState) {
            if ((this.listarClienteOperationCompleted == null)) {
                this.listarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarClienteOperationCompleted);
            }
            this.InvokeAsync("listarCliente", new object[0], this.listarClienteOperationCompleted, userState);
        }
        
        private void OnlistarClienteOperationCompleted(object arg) {
            if ((this.listarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarClienteCompleted(this, new listarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/inserirProduto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void inserirProduto(Produto p) {
            this.Invoke("inserirProduto", new object[] {
                        p});
        }
        
        /// <remarks/>
        public void inserirProdutoAsync(Produto p) {
            this.inserirProdutoAsync(p, null);
        }
        
        /// <remarks/>
        public void inserirProdutoAsync(Produto p, object userState) {
            if ((this.inserirProdutoOperationCompleted == null)) {
                this.inserirProdutoOperationCompleted = new System.Threading.SendOrPostCallback(this.OninserirProdutoOperationCompleted);
            }
            this.InvokeAsync("inserirProduto", new object[] {
                        p}, this.inserirProdutoOperationCompleted, userState);
        }
        
        private void OninserirProdutoOperationCompleted(object arg) {
            if ((this.inserirProdutoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.inserirProdutoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/removerProduto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void removerProduto(Produto p) {
            this.Invoke("removerProduto", new object[] {
                        p});
        }
        
        /// <remarks/>
        public void removerProdutoAsync(Produto p) {
            this.removerProdutoAsync(p, null);
        }
        
        /// <remarks/>
        public void removerProdutoAsync(Produto p, object userState) {
            if ((this.removerProdutoOperationCompleted == null)) {
                this.removerProdutoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoverProdutoOperationCompleted);
            }
            this.InvokeAsync("removerProduto", new object[] {
                        p}, this.removerProdutoOperationCompleted, userState);
        }
        
        private void OnremoverProdutoOperationCompleted(object arg) {
            if ((this.removerProdutoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.removerProdutoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/atualizarProduto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void atualizarProduto(Produto p) {
            this.Invoke("atualizarProduto", new object[] {
                        p});
        }
        
        /// <remarks/>
        public void atualizarProdutoAsync(Produto p) {
            this.atualizarProdutoAsync(p, null);
        }
        
        /// <remarks/>
        public void atualizarProdutoAsync(Produto p, object userState) {
            if ((this.atualizarProdutoOperationCompleted == null)) {
                this.atualizarProdutoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnatualizarProdutoOperationCompleted);
            }
            this.InvokeAsync("atualizarProduto", new object[] {
                        p}, this.atualizarProdutoOperationCompleted, userState);
        }
        
        private void OnatualizarProdutoOperationCompleted(object arg) {
            if ((this.atualizarProdutoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.atualizarProdutoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/listarProduto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Produto[] listarProduto() {
            object[] results = this.Invoke("listarProduto", new object[0]);
            return ((Produto[])(results[0]));
        }
        
        /// <remarks/>
        public void listarProdutoAsync() {
            this.listarProdutoAsync(null);
        }
        
        /// <remarks/>
        public void listarProdutoAsync(object userState) {
            if ((this.listarProdutoOperationCompleted == null)) {
                this.listarProdutoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarProdutoOperationCompleted);
            }
            this.InvokeAsync("listarProduto", new object[0], this.listarProdutoOperationCompleted, userState);
        }
        
        private void OnlistarProdutoOperationCompleted(object arg) {
            if ((this.listarProdutoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarProdutoCompleted(this, new listarProdutoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/inserirServico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void inserirServico(Servico s) {
            this.Invoke("inserirServico", new object[] {
                        s});
        }
        
        /// <remarks/>
        public void inserirServicoAsync(Servico s) {
            this.inserirServicoAsync(s, null);
        }
        
        /// <remarks/>
        public void inserirServicoAsync(Servico s, object userState) {
            if ((this.inserirServicoOperationCompleted == null)) {
                this.inserirServicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OninserirServicoOperationCompleted);
            }
            this.InvokeAsync("inserirServico", new object[] {
                        s}, this.inserirServicoOperationCompleted, userState);
        }
        
        private void OninserirServicoOperationCompleted(object arg) {
            if ((this.inserirServicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.inserirServicoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/removerServico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void removerServico(Servico s) {
            this.Invoke("removerServico", new object[] {
                        s});
        }
        
        /// <remarks/>
        public void removerServicoAsync(Servico s) {
            this.removerServicoAsync(s, null);
        }
        
        /// <remarks/>
        public void removerServicoAsync(Servico s, object userState) {
            if ((this.removerServicoOperationCompleted == null)) {
                this.removerServicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoverServicoOperationCompleted);
            }
            this.InvokeAsync("removerServico", new object[] {
                        s}, this.removerServicoOperationCompleted, userState);
        }
        
        private void OnremoverServicoOperationCompleted(object arg) {
            if ((this.removerServicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.removerServicoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/atualizarServico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void atualizarServico(Servico s) {
            this.Invoke("atualizarServico", new object[] {
                        s});
        }
        
        /// <remarks/>
        public void atualizarServicoAsync(Servico s) {
            this.atualizarServicoAsync(s, null);
        }
        
        /// <remarks/>
        public void atualizarServicoAsync(Servico s, object userState) {
            if ((this.atualizarServicoOperationCompleted == null)) {
                this.atualizarServicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnatualizarServicoOperationCompleted);
            }
            this.InvokeAsync("atualizarServico", new object[] {
                        s}, this.atualizarServicoOperationCompleted, userState);
        }
        
        private void OnatualizarServicoOperationCompleted(object arg) {
            if ((this.atualizarServicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.atualizarServicoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/listarServico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Servico[] listarServico() {
            object[] results = this.Invoke("listarServico", new object[0]);
            return ((Servico[])(results[0]));
        }
        
        /// <remarks/>
        public void listarServicoAsync() {
            this.listarServicoAsync(null);
        }
        
        /// <remarks/>
        public void listarServicoAsync(object userState) {
            if ((this.listarServicoOperationCompleted == null)) {
                this.listarServicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarServicoOperationCompleted);
            }
            this.InvokeAsync("listarServico", new object[0], this.listarServicoOperationCompleted, userState);
        }
        
        private void OnlistarServicoOperationCompleted(object arg) {
            if ((this.listarServicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarServicoCompleted(this, new listarServicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/CadastrarAgendamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CadastrarAgendamento(Agendamento a) {
            this.Invoke("CadastrarAgendamento", new object[] {
                        a});
        }
        
        /// <remarks/>
        public void CadastrarAgendamentoAsync(Agendamento a) {
            this.CadastrarAgendamentoAsync(a, null);
        }
        
        /// <remarks/>
        public void CadastrarAgendamentoAsync(Agendamento a, object userState) {
            if ((this.CadastrarAgendamentoOperationCompleted == null)) {
                this.CadastrarAgendamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarAgendamentoOperationCompleted);
            }
            this.InvokeAsync("CadastrarAgendamento", new object[] {
                        a}, this.CadastrarAgendamentoOperationCompleted, userState);
        }
        
        private void OnCadastrarAgendamentoOperationCompleted(object arg) {
            if ((this.CadastrarAgendamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarAgendamentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AtualizarAgendamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AtualizarAgendamento(Agendamento a) {
            this.Invoke("AtualizarAgendamento", new object[] {
                        a});
        }
        
        /// <remarks/>
        public void AtualizarAgendamentoAsync(Agendamento a) {
            this.AtualizarAgendamentoAsync(a, null);
        }
        
        /// <remarks/>
        public void AtualizarAgendamentoAsync(Agendamento a, object userState) {
            if ((this.AtualizarAgendamentoOperationCompleted == null)) {
                this.AtualizarAgendamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAtualizarAgendamentoOperationCompleted);
            }
            this.InvokeAsync("AtualizarAgendamento", new object[] {
                        a}, this.AtualizarAgendamentoOperationCompleted, userState);
        }
        
        private void OnAtualizarAgendamentoOperationCompleted(object arg) {
            if ((this.AtualizarAgendamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AtualizarAgendamentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/RemoverAgendamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoverAgendamento(Agendamento a) {
            this.Invoke("RemoverAgendamento", new object[] {
                        a});
        }
        
        /// <remarks/>
        public void RemoverAgendamentoAsync(Agendamento a) {
            this.RemoverAgendamentoAsync(a, null);
        }
        
        /// <remarks/>
        public void RemoverAgendamentoAsync(Agendamento a, object userState) {
            if ((this.RemoverAgendamentoOperationCompleted == null)) {
                this.RemoverAgendamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoverAgendamentoOperationCompleted);
            }
            this.InvokeAsync("RemoverAgendamento", new object[] {
                        a}, this.RemoverAgendamentoOperationCompleted, userState);
        }
        
        private void OnRemoverAgendamentoOperationCompleted(object arg) {
            if ((this.RemoverAgendamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoverAgendamentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarAgendamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Agendamento[] ListarAgendamento() {
            object[] results = this.Invoke("ListarAgendamento", new object[0]);
            return ((Agendamento[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarAgendamentoAsync() {
            this.ListarAgendamentoAsync(null);
        }
        
        /// <remarks/>
        public void ListarAgendamentoAsync(object userState) {
            if ((this.ListarAgendamentoOperationCompleted == null)) {
                this.ListarAgendamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarAgendamentoOperationCompleted);
            }
            this.InvokeAsync("ListarAgendamento", new object[0], this.ListarAgendamentoOperationCompleted, userState);
        }
        
        private void OnListarAgendamentoOperationCompleted(object arg) {
            if ((this.ListarAgendamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarAgendamentoCompleted(this, new ListarAgendamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/buscarValor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Servico buscarValor(string cpf) {
            object[] results = this.Invoke("buscarValor", new object[] {
                        cpf});
            return ((Servico)(results[0]));
        }
        
        /// <remarks/>
        public void buscarValorAsync(string cpf) {
            this.buscarValorAsync(cpf, null);
        }
        
        /// <remarks/>
        public void buscarValorAsync(string cpf, object userState) {
            if ((this.buscarValorOperationCompleted == null)) {
                this.buscarValorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarValorOperationCompleted);
            }
            this.InvokeAsync("buscarValor", new object[] {
                        cpf}, this.buscarValorOperationCompleted, userState);
        }
        
        private void OnbuscarValorOperationCompleted(object arg) {
            if ((this.buscarValorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarValorCompleted(this, new buscarValorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/CadastrarPagamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CadastrarPagamento(Pagamento p) {
            this.Invoke("CadastrarPagamento", new object[] {
                        p});
        }
        
        /// <remarks/>
        public void CadastrarPagamentoAsync(Pagamento p) {
            this.CadastrarPagamentoAsync(p, null);
        }
        
        /// <remarks/>
        public void CadastrarPagamentoAsync(Pagamento p, object userState) {
            if ((this.CadastrarPagamentoOperationCompleted == null)) {
                this.CadastrarPagamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarPagamentoOperationCompleted);
            }
            this.InvokeAsync("CadastrarPagamento", new object[] {
                        p}, this.CadastrarPagamentoOperationCompleted, userState);
        }
        
        private void OnCadastrarPagamentoOperationCompleted(object arg) {
            if ((this.CadastrarPagamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarPagamentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/RemoverPagamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoverPagamento(Pagamento p) {
            this.Invoke("RemoverPagamento", new object[] {
                        p});
        }
        
        /// <remarks/>
        public void RemoverPagamentoAsync(Pagamento p) {
            this.RemoverPagamentoAsync(p, null);
        }
        
        /// <remarks/>
        public void RemoverPagamentoAsync(Pagamento p, object userState) {
            if ((this.RemoverPagamentoOperationCompleted == null)) {
                this.RemoverPagamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoverPagamentoOperationCompleted);
            }
            this.InvokeAsync("RemoverPagamento", new object[] {
                        p}, this.RemoverPagamentoOperationCompleted, userState);
        }
        
        private void OnRemoverPagamentoOperationCompleted(object arg) {
            if ((this.RemoverPagamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoverPagamentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarPagamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Pagamento[] ListarPagamento() {
            object[] results = this.Invoke("ListarPagamento", new object[0]);
            return ((Pagamento[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarPagamentoAsync() {
            this.ListarPagamentoAsync(null);
        }
        
        /// <remarks/>
        public void ListarPagamentoAsync(object userState) {
            if ((this.ListarPagamentoOperationCompleted == null)) {
                this.ListarPagamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarPagamentoOperationCompleted);
            }
            this.InvokeAsync("ListarPagamento", new object[0], this.ListarPagamentoOperationCompleted, userState);
        }
        
        private void OnListarPagamentoOperationCompleted(object arg) {
            if ((this.ListarPagamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarPagamentoCompleted(this, new ListarPagamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cliente {
        
        private string cpfField;
        
        private string nomeField;
        
        private string telefoneField;
        
        private string bairroField;
        
        private string enderecoField;
        
        private string sexoField;
        
        /// <remarks/>
        public string Cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        public string Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NotaFiscal {
        
        private Servico servicoField;
        
        private Produto produtoField;
        
        private Cliente clienteField;
        
        private System.DateTime dataField;
        
        private System.DateTime horaField;
        
        private string metodo1Field;
        
        private int cod_nfField;
        
        /// <remarks/>
        public Servico Servico {
            get {
                return this.servicoField;
            }
            set {
                this.servicoField = value;
            }
        }
        
        /// <remarks/>
        public Produto Produto {
            get {
                return this.produtoField;
            }
            set {
                this.produtoField = value;
            }
        }
        
        /// <remarks/>
        public Cliente Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Hora {
            get {
                return this.horaField;
            }
            set {
                this.horaField = value;
            }
        }
        
        /// <remarks/>
        public string Metodo1 {
            get {
                return this.metodo1Field;
            }
            set {
                this.metodo1Field = value;
            }
        }
        
        /// <remarks/>
        public int Cod_nf {
            get {
                return this.cod_nfField;
            }
            set {
                this.cod_nfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Servico {
        
        private double precoField;
        
        private string descricaoField;
        
        private int cod_servField;
        
        /// <remarks/>
        public double Preco {
            get {
                return this.precoField;
            }
            set {
                this.precoField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public int Cod_serv {
            get {
                return this.cod_servField;
            }
            set {
                this.cod_servField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Produto {
        
        private double precoField;
        
        private string descricaoField;
        
        private int cod_prodField;
        
        /// <remarks/>
        public double Preco {
            get {
                return this.precoField;
            }
            set {
                this.precoField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public int Cod_prod {
            get {
                return this.cod_prodField;
            }
            set {
                this.cod_prodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Pagamento {
        
        private NotaFiscal notaF1Field;
        
        private Produto produtoField;
        
        private Cliente clienteField;
        
        private System.DateTime dataField;
        
        private System.DateTime horaField;
        
        private int cod_pagField;
        
        /// <remarks/>
        public NotaFiscal NotaF1 {
            get {
                return this.notaF1Field;
            }
            set {
                this.notaF1Field = value;
            }
        }
        
        /// <remarks/>
        public Produto Produto {
            get {
                return this.produtoField;
            }
            set {
                this.produtoField = value;
            }
        }
        
        /// <remarks/>
        public Cliente Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Hora {
            get {
                return this.horaField;
            }
            set {
                this.horaField = value;
            }
        }
        
        /// <remarks/>
        public int Cod_pag {
            get {
                return this.cod_pagField;
            }
            set {
                this.cod_pagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Agendamento {
        
        private System.DateTime dataField;
        
        private System.DateTime horaField;
        
        private Cliente clienteField;
        
        private Servico servicoField;
        
        private int cod_agField;
        
        /// <remarks/>
        public System.DateTime Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Hora {
            get {
                return this.horaField;
            }
            set {
                this.horaField = value;
            }
        }
        
        /// <remarks/>
        public Cliente Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
            }
        }
        
        /// <remarks/>
        public Servico Servico {
            get {
                return this.servicoField;
            }
            set {
                this.servicoField = value;
            }
        }
        
        /// <remarks/>
        public int Cod_ag {
            get {
                return this.cod_agField;
            }
            set {
                this.cod_agField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void inserirClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void removerClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void atualizarCLienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void listarClienteCompletedEventHandler(object sender, listarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void inserirProdutoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void removerProdutoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void atualizarProdutoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void listarProdutoCompletedEventHandler(object sender, listarProdutoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarProdutoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarProdutoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Produto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Produto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void inserirServicoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void removerServicoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void atualizarServicoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void listarServicoCompletedEventHandler(object sender, listarServicoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarServicoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarServicoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Servico[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Servico[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void CadastrarAgendamentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void AtualizarAgendamentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void RemoverAgendamentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ListarAgendamentoCompletedEventHandler(object sender, ListarAgendamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarAgendamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarAgendamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Agendamento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Agendamento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void buscarValorCompletedEventHandler(object sender, buscarValorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarValorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarValorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Servico Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Servico)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void CadastrarPagamentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void RemoverPagamentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ListarPagamentoCompletedEventHandler(object sender, ListarPagamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarPagamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarPagamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Pagamento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Pagamento[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591