//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BarberShopClasses.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Endereco))]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback inserirClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback removerClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback atualizarCLienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback inserirServicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback removerServicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback atualizarServicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarServicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarServicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CadastrarAgendamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoverAgendamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarAgendamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback atualizarAgendamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarAgendamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarValorOperationCompleted;
        
        private System.Threading.SendOrPostCallback CadastrarPagamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarPagamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback iniciarCaixaOperationCompleted;
        
        private System.Threading.SendOrPostCallback atualizarValorAtualOperationCompleted;
        
        private System.Threading.SendOrPostCallback pesquisarCaixaOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarCaixaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::BarberShopClasses.Properties.Settings.Default.BarberShopClasses_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event inserirClienteCompletedEventHandler inserirClienteCompleted;
        
        /// <remarks/>
        public event removerClienteCompletedEventHandler removerClienteCompleted;
        
        /// <remarks/>
        public event atualizarCLienteCompletedEventHandler atualizarCLienteCompleted;
        
        /// <remarks/>
        public event listarClienteCompletedEventHandler listarClienteCompleted;
        
        /// <remarks/>
        public event buscarClienteCompletedEventHandler buscarClienteCompleted;
        
        /// <remarks/>
        public event inserirServicoCompletedEventHandler inserirServicoCompleted;
        
        /// <remarks/>
        public event removerServicoCompletedEventHandler removerServicoCompleted;
        
        /// <remarks/>
        public event atualizarServicoCompletedEventHandler atualizarServicoCompleted;
        
        /// <remarks/>
        public event listarServicoCompletedEventHandler listarServicoCompleted;
        
        /// <remarks/>
        public event buscarServicoCompletedEventHandler buscarServicoCompleted;
        
        /// <remarks/>
        public event CadastrarAgendamentoCompletedEventHandler CadastrarAgendamentoCompleted;
        
        /// <remarks/>
        public event RemoverAgendamentoCompletedEventHandler RemoverAgendamentoCompleted;
        
        /// <remarks/>
        public event ListarAgendamentoCompletedEventHandler ListarAgendamentoCompleted;
        
        /// <remarks/>
        public event atualizarAgendamentoCompletedEventHandler atualizarAgendamentoCompleted;
        
        /// <remarks/>
        public event buscarAgendamentoCompletedEventHandler buscarAgendamentoCompleted;
        
        /// <remarks/>
        public event buscarValorCompletedEventHandler buscarValorCompleted;
        
        /// <remarks/>
        public event CadastrarPagamentoCompletedEventHandler CadastrarPagamentoCompleted;
        
        /// <remarks/>
        public event ListarPagamentoCompletedEventHandler ListarPagamentoCompleted;
        
        /// <remarks/>
        public event iniciarCaixaCompletedEventHandler iniciarCaixaCompleted;
        
        /// <remarks/>
        public event atualizarValorAtualCompletedEventHandler atualizarValorAtualCompleted;
        
        /// <remarks/>
        public event pesquisarCaixaCompletedEventHandler pesquisarCaixaCompleted;
        
        /// <remarks/>
        public event listarCaixaCompletedEventHandler listarCaixaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/inserirCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void inserirCliente(Cliente c) {
            this.Invoke("inserirCliente", new object[] {
                        c});
        }
        
        /// <remarks/>
        public void inserirClienteAsync(Cliente c) {
            this.inserirClienteAsync(c, null);
        }
        
        /// <remarks/>
        public void inserirClienteAsync(Cliente c, object userState) {
            if ((this.inserirClienteOperationCompleted == null)) {
                this.inserirClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OninserirClienteOperationCompleted);
            }
            this.InvokeAsync("inserirCliente", new object[] {
                        c}, this.inserirClienteOperationCompleted, userState);
        }
        
        private void OninserirClienteOperationCompleted(object arg) {
            if ((this.inserirClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.inserirClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/removerCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void removerCliente(Cliente c) {
            this.Invoke("removerCliente", new object[] {
                        c});
        }
        
        /// <remarks/>
        public void removerClienteAsync(Cliente c) {
            this.removerClienteAsync(c, null);
        }
        
        /// <remarks/>
        public void removerClienteAsync(Cliente c, object userState) {
            if ((this.removerClienteOperationCompleted == null)) {
                this.removerClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoverClienteOperationCompleted);
            }
            this.InvokeAsync("removerCliente", new object[] {
                        c}, this.removerClienteOperationCompleted, userState);
        }
        
        private void OnremoverClienteOperationCompleted(object arg) {
            if ((this.removerClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.removerClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/atualizarCLiente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void atualizarCLiente(Cliente c) {
            this.Invoke("atualizarCLiente", new object[] {
                        c});
        }
        
        /// <remarks/>
        public void atualizarCLienteAsync(Cliente c) {
            this.atualizarCLienteAsync(c, null);
        }
        
        /// <remarks/>
        public void atualizarCLienteAsync(Cliente c, object userState) {
            if ((this.atualizarCLienteOperationCompleted == null)) {
                this.atualizarCLienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnatualizarCLienteOperationCompleted);
            }
            this.InvokeAsync("atualizarCLiente", new object[] {
                        c}, this.atualizarCLienteOperationCompleted, userState);
        }
        
        private void OnatualizarCLienteOperationCompleted(object arg) {
            if ((this.atualizarCLienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.atualizarCLienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/listarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cliente[] listarCliente() {
            object[] results = this.Invoke("listarCliente", new object[0]);
            return ((Cliente[])(results[0]));
        }
        
        /// <remarks/>
        public void listarClienteAsync() {
            this.listarClienteAsync(null);
        }
        
        /// <remarks/>
        public void listarClienteAsync(object userState) {
            if ((this.listarClienteOperationCompleted == null)) {
                this.listarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarClienteOperationCompleted);
            }
            this.InvokeAsync("listarCliente", new object[0], this.listarClienteOperationCompleted, userState);
        }
        
        private void OnlistarClienteOperationCompleted(object arg) {
            if ((this.listarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarClienteCompleted(this, new listarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/buscarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cliente buscarCliente(string cpf) {
            object[] results = this.Invoke("buscarCliente", new object[] {
                        cpf});
            return ((Cliente)(results[0]));
        }
        
        /// <remarks/>
        public void buscarClienteAsync(string cpf) {
            this.buscarClienteAsync(cpf, null);
        }
        
        /// <remarks/>
        public void buscarClienteAsync(string cpf, object userState) {
            if ((this.buscarClienteOperationCompleted == null)) {
                this.buscarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarClienteOperationCompleted);
            }
            this.InvokeAsync("buscarCliente", new object[] {
                        cpf}, this.buscarClienteOperationCompleted, userState);
        }
        
        private void OnbuscarClienteOperationCompleted(object arg) {
            if ((this.buscarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarClienteCompleted(this, new buscarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/inserirServico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void inserirServico(Servico s) {
            this.Invoke("inserirServico", new object[] {
                        s});
        }
        
        /// <remarks/>
        public void inserirServicoAsync(Servico s) {
            this.inserirServicoAsync(s, null);
        }
        
        /// <remarks/>
        public void inserirServicoAsync(Servico s, object userState) {
            if ((this.inserirServicoOperationCompleted == null)) {
                this.inserirServicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OninserirServicoOperationCompleted);
            }
            this.InvokeAsync("inserirServico", new object[] {
                        s}, this.inserirServicoOperationCompleted, userState);
        }
        
        private void OninserirServicoOperationCompleted(object arg) {
            if ((this.inserirServicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.inserirServicoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/removerServico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void removerServico(Servico s) {
            this.Invoke("removerServico", new object[] {
                        s});
        }
        
        /// <remarks/>
        public void removerServicoAsync(Servico s) {
            this.removerServicoAsync(s, null);
        }
        
        /// <remarks/>
        public void removerServicoAsync(Servico s, object userState) {
            if ((this.removerServicoOperationCompleted == null)) {
                this.removerServicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoverServicoOperationCompleted);
            }
            this.InvokeAsync("removerServico", new object[] {
                        s}, this.removerServicoOperationCompleted, userState);
        }
        
        private void OnremoverServicoOperationCompleted(object arg) {
            if ((this.removerServicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.removerServicoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/atualizarServico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void atualizarServico(Servico s) {
            this.Invoke("atualizarServico", new object[] {
                        s});
        }
        
        /// <remarks/>
        public void atualizarServicoAsync(Servico s) {
            this.atualizarServicoAsync(s, null);
        }
        
        /// <remarks/>
        public void atualizarServicoAsync(Servico s, object userState) {
            if ((this.atualizarServicoOperationCompleted == null)) {
                this.atualizarServicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnatualizarServicoOperationCompleted);
            }
            this.InvokeAsync("atualizarServico", new object[] {
                        s}, this.atualizarServicoOperationCompleted, userState);
        }
        
        private void OnatualizarServicoOperationCompleted(object arg) {
            if ((this.atualizarServicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.atualizarServicoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/listarServico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Servico[] listarServico() {
            object[] results = this.Invoke("listarServico", new object[0]);
            return ((Servico[])(results[0]));
        }
        
        /// <remarks/>
        public void listarServicoAsync() {
            this.listarServicoAsync(null);
        }
        
        /// <remarks/>
        public void listarServicoAsync(object userState) {
            if ((this.listarServicoOperationCompleted == null)) {
                this.listarServicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarServicoOperationCompleted);
            }
            this.InvokeAsync("listarServico", new object[0], this.listarServicoOperationCompleted, userState);
        }
        
        private void OnlistarServicoOperationCompleted(object arg) {
            if ((this.listarServicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarServicoCompleted(this, new listarServicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/buscarServico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Servico buscarServico(int cod) {
            object[] results = this.Invoke("buscarServico", new object[] {
                        cod});
            return ((Servico)(results[0]));
        }
        
        /// <remarks/>
        public void buscarServicoAsync(int cod) {
            this.buscarServicoAsync(cod, null);
        }
        
        /// <remarks/>
        public void buscarServicoAsync(int cod, object userState) {
            if ((this.buscarServicoOperationCompleted == null)) {
                this.buscarServicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarServicoOperationCompleted);
            }
            this.InvokeAsync("buscarServico", new object[] {
                        cod}, this.buscarServicoOperationCompleted, userState);
        }
        
        private void OnbuscarServicoOperationCompleted(object arg) {
            if ((this.buscarServicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarServicoCompleted(this, new buscarServicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/CadastrarAgendamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CadastrarAgendamento(Agendamento a) {
            this.Invoke("CadastrarAgendamento", new object[] {
                        a});
        }
        
        /// <remarks/>
        public void CadastrarAgendamentoAsync(Agendamento a) {
            this.CadastrarAgendamentoAsync(a, null);
        }
        
        /// <remarks/>
        public void CadastrarAgendamentoAsync(Agendamento a, object userState) {
            if ((this.CadastrarAgendamentoOperationCompleted == null)) {
                this.CadastrarAgendamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarAgendamentoOperationCompleted);
            }
            this.InvokeAsync("CadastrarAgendamento", new object[] {
                        a}, this.CadastrarAgendamentoOperationCompleted, userState);
        }
        
        private void OnCadastrarAgendamentoOperationCompleted(object arg) {
            if ((this.CadastrarAgendamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarAgendamentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/RemoverAgendamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoverAgendamento(Agendamento a) {
            this.Invoke("RemoverAgendamento", new object[] {
                        a});
        }
        
        /// <remarks/>
        public void RemoverAgendamentoAsync(Agendamento a) {
            this.RemoverAgendamentoAsync(a, null);
        }
        
        /// <remarks/>
        public void RemoverAgendamentoAsync(Agendamento a, object userState) {
            if ((this.RemoverAgendamentoOperationCompleted == null)) {
                this.RemoverAgendamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoverAgendamentoOperationCompleted);
            }
            this.InvokeAsync("RemoverAgendamento", new object[] {
                        a}, this.RemoverAgendamentoOperationCompleted, userState);
        }
        
        private void OnRemoverAgendamentoOperationCompleted(object arg) {
            if ((this.RemoverAgendamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoverAgendamentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarAgendamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Agendamento[] ListarAgendamento() {
            object[] results = this.Invoke("ListarAgendamento", new object[0]);
            return ((Agendamento[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarAgendamentoAsync() {
            this.ListarAgendamentoAsync(null);
        }
        
        /// <remarks/>
        public void ListarAgendamentoAsync(object userState) {
            if ((this.ListarAgendamentoOperationCompleted == null)) {
                this.ListarAgendamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarAgendamentoOperationCompleted);
            }
            this.InvokeAsync("ListarAgendamento", new object[0], this.ListarAgendamentoOperationCompleted, userState);
        }
        
        private void OnListarAgendamentoOperationCompleted(object arg) {
            if ((this.ListarAgendamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarAgendamentoCompleted(this, new ListarAgendamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/atualizarAgendamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void atualizarAgendamento(Agendamento a) {
            this.Invoke("atualizarAgendamento", new object[] {
                        a});
        }
        
        /// <remarks/>
        public void atualizarAgendamentoAsync(Agendamento a) {
            this.atualizarAgendamentoAsync(a, null);
        }
        
        /// <remarks/>
        public void atualizarAgendamentoAsync(Agendamento a, object userState) {
            if ((this.atualizarAgendamentoOperationCompleted == null)) {
                this.atualizarAgendamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnatualizarAgendamentoOperationCompleted);
            }
            this.InvokeAsync("atualizarAgendamento", new object[] {
                        a}, this.atualizarAgendamentoOperationCompleted, userState);
        }
        
        private void OnatualizarAgendamentoOperationCompleted(object arg) {
            if ((this.atualizarAgendamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.atualizarAgendamentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/buscarAgendamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Agendamento buscarAgendamento(string cpf) {
            object[] results = this.Invoke("buscarAgendamento", new object[] {
                        cpf});
            return ((Agendamento)(results[0]));
        }
        
        /// <remarks/>
        public void buscarAgendamentoAsync(string cpf) {
            this.buscarAgendamentoAsync(cpf, null);
        }
        
        /// <remarks/>
        public void buscarAgendamentoAsync(string cpf, object userState) {
            if ((this.buscarAgendamentoOperationCompleted == null)) {
                this.buscarAgendamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarAgendamentoOperationCompleted);
            }
            this.InvokeAsync("buscarAgendamento", new object[] {
                        cpf}, this.buscarAgendamentoOperationCompleted, userState);
        }
        
        private void OnbuscarAgendamentoOperationCompleted(object arg) {
            if ((this.buscarAgendamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarAgendamentoCompleted(this, new buscarAgendamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/buscarValor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Servico buscarValor(string cpf) {
            object[] results = this.Invoke("buscarValor", new object[] {
                        cpf});
            return ((Servico)(results[0]));
        }
        
        /// <remarks/>
        public void buscarValorAsync(string cpf) {
            this.buscarValorAsync(cpf, null);
        }
        
        /// <remarks/>
        public void buscarValorAsync(string cpf, object userState) {
            if ((this.buscarValorOperationCompleted == null)) {
                this.buscarValorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarValorOperationCompleted);
            }
            this.InvokeAsync("buscarValor", new object[] {
                        cpf}, this.buscarValorOperationCompleted, userState);
        }
        
        private void OnbuscarValorOperationCompleted(object arg) {
            if ((this.buscarValorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarValorCompleted(this, new buscarValorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/CadastrarPagamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CadastrarPagamento(Pagamento p) {
            this.Invoke("CadastrarPagamento", new object[] {
                        p});
        }
        
        /// <remarks/>
        public void CadastrarPagamentoAsync(Pagamento p) {
            this.CadastrarPagamentoAsync(p, null);
        }
        
        /// <remarks/>
        public void CadastrarPagamentoAsync(Pagamento p, object userState) {
            if ((this.CadastrarPagamentoOperationCompleted == null)) {
                this.CadastrarPagamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarPagamentoOperationCompleted);
            }
            this.InvokeAsync("CadastrarPagamento", new object[] {
                        p}, this.CadastrarPagamentoOperationCompleted, userState);
        }
        
        private void OnCadastrarPagamentoOperationCompleted(object arg) {
            if ((this.CadastrarPagamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarPagamentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarPagamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Pagamento[] ListarPagamento() {
            object[] results = this.Invoke("ListarPagamento", new object[0]);
            return ((Pagamento[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarPagamentoAsync() {
            this.ListarPagamentoAsync(null);
        }
        
        /// <remarks/>
        public void ListarPagamentoAsync(object userState) {
            if ((this.ListarPagamentoOperationCompleted == null)) {
                this.ListarPagamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarPagamentoOperationCompleted);
            }
            this.InvokeAsync("ListarPagamento", new object[0], this.ListarPagamentoOperationCompleted, userState);
        }
        
        private void OnListarPagamentoOperationCompleted(object arg) {
            if ((this.ListarPagamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarPagamentoCompleted(this, new ListarPagamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/iniciarCaixa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void iniciarCaixa(Caixa cx) {
            this.Invoke("iniciarCaixa", new object[] {
                        cx});
        }
        
        /// <remarks/>
        public void iniciarCaixaAsync(Caixa cx) {
            this.iniciarCaixaAsync(cx, null);
        }
        
        /// <remarks/>
        public void iniciarCaixaAsync(Caixa cx, object userState) {
            if ((this.iniciarCaixaOperationCompleted == null)) {
                this.iniciarCaixaOperationCompleted = new System.Threading.SendOrPostCallback(this.OniniciarCaixaOperationCompleted);
            }
            this.InvokeAsync("iniciarCaixa", new object[] {
                        cx}, this.iniciarCaixaOperationCompleted, userState);
        }
        
        private void OniniciarCaixaOperationCompleted(object arg) {
            if ((this.iniciarCaixaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.iniciarCaixaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/atualizarValorAtual", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void atualizarValorAtual(Caixa cx) {
            this.Invoke("atualizarValorAtual", new object[] {
                        cx});
        }
        
        /// <remarks/>
        public void atualizarValorAtualAsync(Caixa cx) {
            this.atualizarValorAtualAsync(cx, null);
        }
        
        /// <remarks/>
        public void atualizarValorAtualAsync(Caixa cx, object userState) {
            if ((this.atualizarValorAtualOperationCompleted == null)) {
                this.atualizarValorAtualOperationCompleted = new System.Threading.SendOrPostCallback(this.OnatualizarValorAtualOperationCompleted);
            }
            this.InvokeAsync("atualizarValorAtual", new object[] {
                        cx}, this.atualizarValorAtualOperationCompleted, userState);
        }
        
        private void OnatualizarValorAtualOperationCompleted(object arg) {
            if ((this.atualizarValorAtualCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.atualizarValorAtualCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/pesquisarCaixa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Caixa pesquisarCaixa(int cod) {
            object[] results = this.Invoke("pesquisarCaixa", new object[] {
                        cod});
            return ((Caixa)(results[0]));
        }
        
        /// <remarks/>
        public void pesquisarCaixaAsync(int cod) {
            this.pesquisarCaixaAsync(cod, null);
        }
        
        /// <remarks/>
        public void pesquisarCaixaAsync(int cod, object userState) {
            if ((this.pesquisarCaixaOperationCompleted == null)) {
                this.pesquisarCaixaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpesquisarCaixaOperationCompleted);
            }
            this.InvokeAsync("pesquisarCaixa", new object[] {
                        cod}, this.pesquisarCaixaOperationCompleted, userState);
        }
        
        private void OnpesquisarCaixaOperationCompleted(object arg) {
            if ((this.pesquisarCaixaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pesquisarCaixaCompleted(this, new pesquisarCaixaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/listarCaixa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Caixa[] listarCaixa() {
            object[] results = this.Invoke("listarCaixa", new object[0]);
            return ((Caixa[])(results[0]));
        }
        
        /// <remarks/>
        public void listarCaixaAsync() {
            this.listarCaixaAsync(null);
        }
        
        /// <remarks/>
        public void listarCaixaAsync(object userState) {
            if ((this.listarCaixaOperationCompleted == null)) {
                this.listarCaixaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarCaixaOperationCompleted);
            }
            this.InvokeAsync("listarCaixa", new object[0], this.listarCaixaOperationCompleted, userState);
        }
        
        private void OnlistarCaixaOperationCompleted(object arg) {
            if ((this.listarCaixaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarCaixaCompleted(this, new listarCaixaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Pagamento))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cliente : Endereco {
        
        private string cpfField;
        
        private string nomeField;
        
        private string telefoneField;
        
        private string sexoField;
        
        /// <remarks/>
        public string Cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cliente))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Pagamento))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Endereco {
        
        private string cepField;
        
        private string ruaField;
        
        private string numeroField;
        
        private string bairroField;
        
        private string cidadeField;
        
        private string ufField;
        
        /// <remarks/>
        public string Cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        public string Rua {
            get {
                return this.ruaField;
            }
            set {
                this.ruaField = value;
            }
        }
        
        /// <remarks/>
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Caixa {
        
        private decimal valor_inicialField;
        
        private decimal valor_finalField;
        
        private decimal valor_atualField;
        
        private int cod_caixaField;
        
        private string dataField;
        
        private string horaField;
        
        /// <remarks/>
        public decimal Valor_inicial {
            get {
                return this.valor_inicialField;
            }
            set {
                this.valor_inicialField = value;
            }
        }
        
        /// <remarks/>
        public decimal Valor_final {
            get {
                return this.valor_finalField;
            }
            set {
                this.valor_finalField = value;
            }
        }
        
        /// <remarks/>
        public decimal Valor_atual {
            get {
                return this.valor_atualField;
            }
            set {
                this.valor_atualField = value;
            }
        }
        
        /// <remarks/>
        public int Cod_caixa {
            get {
                return this.cod_caixaField;
            }
            set {
                this.cod_caixaField = value;
            }
        }
        
        /// <remarks/>
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public string Hora {
            get {
                return this.horaField;
            }
            set {
                this.horaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Agendamento {
        
        private string dataField;
        
        private string horaField;
        
        private Cliente clienteField;
        
        private Servico servicoField;
        
        private int cod_agField;
        
        /// <remarks/>
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public string Hora {
            get {
                return this.horaField;
            }
            set {
                this.horaField = value;
            }
        }
        
        /// <remarks/>
        public Cliente Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
            }
        }
        
        /// <remarks/>
        public Servico Servico {
            get {
                return this.servicoField;
            }
            set {
                this.servicoField = value;
            }
        }
        
        /// <remarks/>
        public int Cod_ag {
            get {
                return this.cod_agField;
            }
            set {
                this.cod_agField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Servico {
        
        private double precoField;
        
        private string descricaoField;
        
        private int cod_servField;
        
        /// <remarks/>
        public double Preco {
            get {
                return this.precoField;
            }
            set {
                this.precoField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public int Cod_serv {
            get {
                return this.cod_servField;
            }
            set {
                this.cod_servField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Pagamento : Cliente {
        
        private string dataField;
        
        private string horaField;
        
        private string metodoField;
        
        private decimal valorField;
        
        private int cod_caixaField;
        
        /// <remarks/>
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public string Hora {
            get {
                return this.horaField;
            }
            set {
                this.horaField = value;
            }
        }
        
        /// <remarks/>
        public string Metodo {
            get {
                return this.metodoField;
            }
            set {
                this.metodoField = value;
            }
        }
        
        /// <remarks/>
        public decimal Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        public int Cod_caixa {
            get {
                return this.cod_caixaField;
            }
            set {
                this.cod_caixaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void inserirClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void removerClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void atualizarCLienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void listarClienteCompletedEventHandler(object sender, listarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void buscarClienteCompletedEventHandler(object sender, buscarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void inserirServicoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void removerServicoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void atualizarServicoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void listarServicoCompletedEventHandler(object sender, listarServicoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarServicoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarServicoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Servico[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Servico[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void buscarServicoCompletedEventHandler(object sender, buscarServicoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarServicoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarServicoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Servico Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Servico)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void CadastrarAgendamentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void RemoverAgendamentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ListarAgendamentoCompletedEventHandler(object sender, ListarAgendamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarAgendamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarAgendamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Agendamento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Agendamento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void atualizarAgendamentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void buscarAgendamentoCompletedEventHandler(object sender, buscarAgendamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarAgendamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarAgendamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Agendamento Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Agendamento)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void buscarValorCompletedEventHandler(object sender, buscarValorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarValorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarValorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Servico Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Servico)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void CadastrarPagamentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ListarPagamentoCompletedEventHandler(object sender, ListarPagamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarPagamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarPagamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Pagamento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Pagamento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void iniciarCaixaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void atualizarValorAtualCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void pesquisarCaixaCompletedEventHandler(object sender, pesquisarCaixaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pesquisarCaixaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pesquisarCaixaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Caixa Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Caixa)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void listarCaixaCompletedEventHandler(object sender, listarCaixaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarCaixaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarCaixaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Caixa[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Caixa[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591